packages:
  - packages/*
  - examples/*
  - docs

onlyBuiltDependencies:
  - esbuild
  - sharp

publishBranch: main

catalog:
  typescript: ^5.8.3
  "@types/node": ^22.16.3
  vitest: ^3.2.4
  tsx: ^4.20.5
